export const FETCH_ADDED_CITIES_START = 'FETCH_ADDED_CITIES_START'
export const FETCH_ADDED_CITIES_SUCCESS = 'FETCH_ADDED_CITIES_SUCCESS'
export const FETCH_ADDED_CITIES_FAILURE = 'FETCH_ADDED_CITIES_FAILURE'

export const FETCH_CITIES_START = 'FETCH_CITIES_START'
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS'
export const FETCH_CITIES_FAILURE = 'FETCH_CITIES_FAILURE'

export const ADD_CITY_START = 'ADD_CITY_START'
export const ADD_CITY_SUCCESS = 'ADD_CITY_SUCCESS'
export const ADD_CITY_FAILURE = 'ADD_CITY_FAILURE'

export const FETCH_WEATHER_START = 'FETCH_WEATHER_START'
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS'

export const REMOVE_CITY = 'REMOVE_CITY'
